# Generated by Django 4.0.3 on 2022-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
