# Generated by Django 4.0.3 on 2022-03-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='role',
            field=models.CharField(default='developer', max_length=15),
        ),
    ]
