# Generated by Django 4.0.3 on 2022-03-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bio_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='stacks_used',
            field=models.CharField(default='null', max_length=75, null=True),
        ),
    ]
