# Generated by Django 4.0.3 on 2022-04-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_portfolio_stacks_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='bio',
            field=models.CharField(default='null', max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='stack',
            field=models.CharField(default='web developer', max_length=15),
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
