# Generated by Django 4.0.3 on 2022-04-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_bio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
