# Generated by Django 3.2.12 on 2022-04-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(default='Django', max_length=50),
        ),
    ]
