# Generated by Django 3.2.12 on 2022-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_project_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='linkedin',
            field=models.CharField(default='null', max_length=75),
        ),
    ]
