# Generated by Django 3.2.12 on 2022-05-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
