# Generated by Django 3.2.12 on 2022-05-08 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='title', max_length=35),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 8, 16, 29, 57, 664450)),
        ),
        migrations.AddField(
            model_name='comment',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 8, 16, 29, 57, 665446)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
