# Generated by Django 3.2.12 on 2022-05-08 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20220508_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='uploaded',
            field=models.DateTimeField(blank=True, default='2022-05-08 17:55:54.349667'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 8, 17, 56, 54, 847415)),
        ),
    ]
