# Generated by Django 3.2.12 on 2022-06-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_blogpost_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default='hardware', max_length=35),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='type',
            field=models.CharField(default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='static/accounts/images/chain.png', null=True, upload_to='images/'),
        ),
    ]
